spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: academy
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5 # Número máximo de conexiones en el pool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true